// SvelteKit + Cloudflare Worker ambient types.
//
// `Cloudflare.Env` is generated by `wrangler types` into worker-configuration.d.ts
// from wrangler.jsonc bindings. We augment it here with optional secrets that
// are not declared in wrangler's `secrets.required` list (the optional provider
// API keys read at runtime by `routeLLM` / settings). Add new optional secrets
// to this list when introducing them.

declare global {
	namespace App {
		// Surfaced via `event.platform.env` in load functions, hooks, +server.ts,
		// and remote functions.
		interface Platform {
			env: Cloudflare.Env;
			cf: CfProperties;
			ctx: ExecutionContext;
		}
		interface Locals {
			theme: 'system' | 'light' | 'dark';
		}
		interface PageData {}
		interface PageState {}
		interface Error {}
	}

	namespace Cloudflare {
		interface Env {
			// Wrangler types `CONVERSATION_DURABLE_OBJECT` as a bare
			// `DurableObjectNamespace` (no generic) because the SvelteKit
			// adapter's bundled worker file isn't a TS-resolvable module.
			// `getConversationStub()` in `$lib/server/durable_objects` returns
			// the typed view; reach for that instead of the binding directly.
			ANTHROPIC_KEY?: string;
			OPENAI_KEY?: string;
			GOOGLE_KEY?: string;
			DEEPSEEK_KEY?: string;
			KAGI_KEY?: string;
			YNAB_TOKEN?: string;
		}
	}
}

export {};
